### DISCUSSION TITLE
Excessive memory usage for long periods of time (>1g)

### DISCUSSION THREAD

**Discussion by ruibaby** [umami-software/umami#1237] [Q&A]
## Description

The memory usage is up to 1g or more for a long time. This has not happened before, and this is the second time it has happened in a while. Normal after reboot.

docker stats:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/21301288/166923717-2a7c7ce3-142a-4603-a08f-42f864110d12.png">

bpytop:

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/21301288/166923782-fc43bb27-3517-4336-80d9-7e2688b07af0.png">

Realtime:

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/21301288/166924682-e19c717c-6729-42b9-b713-681d8d867e0c.png">

Dashboard:

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/21301288/166924825-4ecb171b-be56-485a-b910-41de41890d55.png">

Database:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/21301288/166925741-b3f587bc-846f-48d7-8ae4-1d5081bcd884.png">
<img width="367" alt="image" src="https://user-images.githubusercontent.com/21301288/166925806-f579c902-df8d-476a-b780-508d811b784d.png">

## Deployment way

Docker Compose:

```yaml
---
version: '3'
services:
  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    ports:
      - "4000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: BPqwV9uJ@trNtQt2F5RknP$mhoLt7$JJ2Y#GA84k
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
    restart: always
volumes:
  umami-db-data:
```
