### DISCUSSION TITLE
Add fly.io Documentation and Setup

### DISCUSSION THREAD

**Discussion by laupski** [umami-software/umami#1275] [General]
Hey Mike,

I ended up installing and getting up and running umami on fly.io . The thread from their forums is located here: https://community.fly.io/t/deploying-umami/5117 I was pleasantly surprised how easy it was and it's all in their free tier.

Would you want a PR on this setup? I'm not exactly sure where the documentation for the hosting sites is located. The 2nd problem is that fly.io's best practices are based on using Dockerfiles so the two options would be to is modify the current Dockerfile on the default branch (hard) or creating a new Dockerfile.fly.io file (easier but more annoying to maintain). Let me know your thoughts.

**Comment by mikecao** [comment]
Awesome! Yes, I would welcome a PR. The website repo is here, https://github.com/mikecao/umami.is

**Comment by danielslyman** [comment]
Hey guys, I wanted to check up on whether this is actually stable and working? Fly.io looks amazing!

**Comment by CanRau** [comment]
I installed Umami on fly without any special workaround or sthg, used created a Fly postgre db and linked it to the Umami app which using the following `fly.toml`

```toml
app = "APP_NAME"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "ghcr.io/umami-software/umami:postgresql-latest"

[env]
  DATABASE_TYPE = "postgresql"
  # TRACKER_SCRIPT_NAME = 
  # COLLECT_API_ENDPOINT = 
  DISABLE_UPDATES = 0

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
```
