### DISCUSSION TITLE
Umami behind Traefik Reverse Proxy in K3s not gathering Countries Stats

### DISCUSSION THREAD

**Discussion by Dan6erbond** [umami-software/umami#1777] [Q&A] [answered]
Hello everyone! Really love Umami and how quick and easy it was to setup. Unfortunately, I'm having one issue with it, which is that Umami isn't collecting any data about countries of my website visitors. I have Umami deployed in K3s which uses [Traefik](https://docs.k3s.io/networking) as the default reverse proxy.

My custom Traefik configuration is this `HelmChartConfig` that modifies some of the default values:

```yml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=ravianand.me"
      - "--certificatesresolvers.letsencrypt.acme.tlsChallenge"
      - "--certificatesresolvers.letsencrypt.acme.email=moravrav@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--experimental.plugins.htransformation.modulename=github.com/tomMoulard/htransformation"
      - "--experimental.plugins.htransformation.version=v0.2.7"
    ports:
      web:
        redirectTo: websecure
    persistence:
      enabled: true
      storageClass: local-path
      path: /data
    logs:
      access:
        enabled: true
    experimental:
      plugins:
        enabled: true
```

Other than that no changes have been made to my Traefik config. I've seen other people have this issue with Docker/Docker Swarm, where the fix was to use host networking instead of the Ingress, but I don't think this applies for Kubernetes `LoadBalancer`, and I've tried various configurations to force Traefik to pass the `X-Forwarded-` headers to no avail.

Has anyone gotten Umami working in Kubernetes with Traefik?

**Comment by Dan6erbond** [comment, marked as answer]
I was able to fix it, after I found this [thread](https://forums.rancher.com/t/k3s-and-x-forwarded-for-header-in-traefik-18-1/19283) that suggests setting `externalTrafficPolicy: Local` since Kubernetes will otherwise use Cluster which results in an obscured client IP.

For those using the Traefik Helm chart, add this to your config:

```yml
    service:
      spec:
        externalTrafficPolicy: Local
```

[More on Kubernetes LoadBalancer.](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/)
