### DISCUSSION TITLE
Working Traefik front end proxy + Umami docker-compose.yml file?

### DISCUSSION THREAD

**Discussion by anseltaft** [umami-software/umami#2282] [General]
Hi All 👋

May I ask someone to please post their working Traefik front end proxy + Umami docker-compose.yml file?

I had separate, working docker-compose.yml files for both Traefik and Umami but the original host took a nose dive last week (Dedipath, IYKYK) so I spun up a VPS on a new host, used the same OS (Debian 11), rebuilt the environment, and launched the containers with Docker Compose. At this point I've tried a few dozen docker-compose.yml, re-imaged and rebuilt the VPS twice, nuked the docker images so many times I've lost count, and worked through the errors as they've popped up but I can't get Umami to come up and fully working.

So I'm hoping for someone to post their "known good" script for me to work from with normal things redacted such as the host URL, app salts nuked... I can fill all that stuff back in, no worries.

Thank you in advance for any help.

**Comment by anseltaft** [comment]
Here's my traefik docker-compose.yml file I ended up with after discovering I needed to use the --force-recreate tag to get docker compose to pick up the changes. I adapted [Techno Tim's Traefik docker-compose.yml](https://github.com/techno-tim/techno-tim.github.io/blob/master/reference_files/traefik-portainer-ssl/traefik/docker-compose.yml) for the front end proxy and used the labels from his [Portainer docker-compose.yml](https://github.com/techno-tim/techno-tim.github.io/blob/master/reference_files/traefik-portainer-ssl/portainer/docker-compose.yml) file.

```
services:
  umami:
    image: docker.umami.dev/umami-software/umami:postgresql-latest
    container_name: umami
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - umami_default
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://umami:MAKE-A-PASSWORD@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: ADD-A-SALT-STRING-HERE
      TRACKER_SCRIPT_NAME: my-script-name.js
      IGNORE_IP: ADD-YOUR-HOME-OR-WORK-IP-HERE
      NODE_VERSION: 20.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.umami.entrypoints=http"
      - "traefik.http.routers.umami.rule=Host(`subdomain.mydomain.com`)"
      - "traefik.http.middlewares.umami-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.umami.middlewares=umami-https-redirect"
      - "traefik.http.routers.umami-secure.entrypoints=https"
      - "traefik.http.routers.umami-secure.rule=Host(`subdomain.mydomain.com`)"
      - "traefik.http.routers.umami-secure.tls=true"
      - "traefik.http.routers.umami-secure.service=umami"
      - "traefik.http.services.umami.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
  db:
    image: postgres:12-alpine
    container_name: umami-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - umami_default
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: MAKE-A-PASSWORD
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
volumes:
  umami-db-data:

networks:
  proxy:
    external: true
  umami_default:
    external: true
```
