### DISCUSSION TITLE
Need help with ALLOWED_FRAME_URLS

### DISCUSSION THREAD

**Discussion by sfxter** [umami-software/umami#2792] [Q&A]
I can't get to work ALLOWED_FRAME_URLS env setting. For the last couple of hours I'm trying to figure it out without any success. Here is my docker-compose file, where I enter ALLOWED_FRAME_URLS env, but it does not work - I still cannot see Content-Security-Policy change in headers. 
```

version: "3"
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      TRACKER_SCRIPT_NAME: getinfo
      ALLOWED_FRAME_URLS: https://mydomain.com
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: my-secret-hash
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - /docker/umami/db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  umami-db-data:

```

Any help would be appreciated.
