### DISCUSSION TITLE
Countries stats in docker swarm environment with traefik/ nginx reverse proxy

### DISCUSSION THREAD

**Discussion by OCram85** [umami-software/umami#947] [Q&A] [answered]
Hello umami community,
I'm running umami as docker swarm service with traefik as reverse proxy.

Does anyone managed to get valid country stats in such setup?

![image](https://user-images.githubusercontent.com/13993700/152512273-e804cdba-b0fa-430d-b74d-71629460a9f2.png)

I assume the reverse proxy doesn't pass the real client IPs. Unfortunately I tested it with nginx and had the same issue.

**Comment by animesh-workplace** [comment]
Did anyone find a solution for this? @OCram85 

I'm also facing the same problem.

**Comment by mikecao** [comment]
See https://github.com/mikecao/umami/issues/814. You may need to use a custom header value.

**Reply by animesh-workplace** [reply]
Thank you @mikecao. Now it's working

**Comment by OCram85** [comment]
Did anyone solved this with traefik as reverse proxy?

**Comment by OCram85** [comment, marked as answer]
Just solved it:

traefik normally runs in docker swarm on a `overlay` network. The ports are published like this:

```yaml
version: "3.8"
services:
  ...
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    restart: unless-stopped
    networks:
      - "traefik-public"
    ports:
      #- "80:80"
      #- "443:443"
...
networks:
  traefik-public:
    name: traefik-public
    external: true
    attachable: true
```

But the port-binding must be done via the host:

```yaml
ports:
  #- "80:80"
  #- "443:443"
  - target: 80
    published: 80
    protocol: tcp
    mode: host
  - target: 443
    published: 443
    protocol: tcp
    mode: host
```

> 💡 NOTE: By publishing a port in `host` mode you bypass the swarm `ingress` network. Thus, you have to use your own loadbalancer like haproxy. See: https://docs.docker.com/engine/swarm/ingress/#using-the-routing-mesh for details. Alternatively, you could implement a custom ingress network controller: https://github.com/newsnowlabs/docker-ingress-routing-daemon
