### ISSUE TITLE
DISABLE_LOGIN doesn't disable the login screen

### ISSUE THREAD

**Issue by Luca-Castelnuovo** [umami-software/umami#1259]
Hi,

I've set the DISABLE_LOGIN var to true.
When I open the `localhost:3000` I get redirected to `localhost:3000/login` and prompted for credentials.

Is this a bug or did I do something wrong?

**docker-compose.yml** (example values used for the secrets)
```yaml
version: "3"

services:
  stats:
    image: ghcr.io/umami-software/umami:mysql-v1.33.3
    container_name: stats
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      DATABASE_URL: mysql://root:root@mariadb:3306/defaultdb
      DATABASE_TYPE: mysql
      HASH_SALT: 8FF29D3FFB69D879D7293D256EDABF49DD8AC139F17B344766F8D7D2AA
      DISABLE_LOGIN: true
      DISABLE_TELEMETRY: true
      REMOVE_TRAILING_SLASH: true
      TRACKER_SCRIPT_NAME: stats
      HOSTNAME: stats.castelnuovo.xyz
    ports:
      - 3000:3000
```
