### ISSUE TITLE
COLLECT_API_ENDPOINT does not work

### ISSUE THREAD

**Issue by leirock** [umami-software/umami#1318]
I just upgraded umami to v1.34.0 and set the environment variable `COLLECT_API_ENDPOINT: '/api/x'` in docker-compose settings. 

```yaml
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    environment:
      TRACKER_SCRIPT_NAME: 'script'
      COLLECT_API_ENDPOINT: '/api/x'
```

But this environment variable seems does not work. In my [tracker script](https://stat.pinlyu.com/script.js), the endpoint is still `/api/collect`. I tried to clear cookies and restarted the docker container, but nothing changed.

**Comment by AntoninHuaut** [comment]
I have the same problem

**Comment by mikecao** [comment]
Just updated the documentation to make this more clear, but `COLLECT_API_ENDPOINT` is a build time variable. So you will need to rebuild the application for it to take effect. See https://umami.is/docs/environment-variables

**Comment by mikecao** [comment]
Should be fixed in v1.35.0.

**Comment by leirock** [comment]
> Just updated the documentation to make this more clear, but `COLLECT_API_ENDPOINT` is a build time variable. So you will need to rebuild the application for it to take effect. See https://umami.is/docs/environment-variables

@mikecao I don't know how to set a build time variable in the docker-compose file. 

For the runtime variables such as `TRACKER_SCRIPT_NAME`, I can set like this:

```yaml
services:
  umami:
    environment:
      TRACKER_SCRIPT_NAME: 'script'
```

But how about a build time variable in v1.35.0?
