### ISSUE TITLE
Realtime page is blank (error 500)

### ISSUE THREAD

**Issue by leirock** [umami-software/umami#1436]
After I upgraded umami to v1.37.0, the Realtime page is blank and cannot load diagrams (screenshot is as follows). But the number of realtime visitors can be showed on Dashboard page. 

The error code in browser is 500. `GET .../api/realtime/init 500`

My docker configuration is:

```yaml
version: '3'
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    ports:
      - '8030:3000'
    environment:
      IGNORE_IP: '127.0.0.1'
      TRACKER_SCRIPT_NAME: 'script'
      DATABASE_URL: postgresql://umami:Wxxxxxx@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: sdxxx
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12-alpine
    container_name: umami_db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: Wxxxxx
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  umami-db-data:
```

<img width="550" alt="image" src="https://user-images.githubusercontent.com/19180725/184869875-df89cfea-b740-4691-8a5b-9cd24be5abbf.png">
