### ISSUE TITLE
Unable to connect to the database (latest version)

### ISSUE THREAD

**Issue by HipyCas** [umami-software/umami#1743]
I wanted to test umami to use with some webapps that I was developing, but I had no success with it. I have tried both mysql and postgress setups according to the documentation, and none have worked. The error I get in both is the following:

```
yarn run v1.22.19
$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✗ Unable to connect to the database.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "check-db" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

When looking into the logs of the DB, everything seems to be working perfectly.

### My MySQL configuration (with MariaDB):

```yaml
  umami:
    image: ghcr.io/umami-software/umami:mysql-latest
    ports:
      - "3009:3000"
    environment:
      DATABASE_URL: mysql://umami:umami@db:3306/umami
      DATABASE_TYPE: mysql
      HASH_SALT: b493eAA+mMZ8SDzR9qq6xIHRC4dvCUACKR9VnwEeyNU=
    depends_on:
      - umami-db
    restart: always
  umami-db:
    image: mariadb:10.5
    restart: always
    volumes:
      - ./umami/db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_USER=umami
      - MARIADB_PASSWORD=umami
      - MARIADB_DATABASE=umami
```

I have tried both with the `DATABASE_TYPE` env var and without and also tried exposing MariaDB's ports, no success.

### Postgress configuration (exactly as the docker-compose in this repo):

```yaml
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: b493eAA+mMZ8SDzR9qq6xIHRC4dvCUACKR9VnwEeyNU=
    depends_on:
      - umami-db
    restart: always
  umami-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - ./umami/dbdata:/var/lib/postgresql/data
    restart: always
```

**As a suggestion**, I believe the `check-db.js` script could output some info on the process and the error, so debugging is easier and maybe I wouldn't have needed to file an issue for this.

**Comment by Aewait** [comment]
> You can try 'prisma migrate deploy' if you want to get the internal prisma error.
> 
> But it looks like you changed the container name to `umami-db` while leaving the connection string as `db`.
> 
> Try:
> 
> ```
> mysql://umami:umami@umami-db:3306/umami
> 
> or
> 
> postgresql://umami:umami@umami-db:5432/umami
> ```

same issue for me 
```
umami_1   | yarn run v1.22.19
umami_1   | $ npm-run-all check-db update-tracker start-server
umami_1   | $ node scripts/check-db.js
umami_1   | ✓ DATABASE_URL is defined.
umami_1   | ✗ Unable to connect to the database.
umami_1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
umami_1   | error Command failed with exit code 1.
umami_1   | ERROR: "check-db" exited with 1.
umami_1   | error Command failed with exit code 1.
umami_1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
my docker-compose.yml
```
version: '3'
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3010:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@umi-db:5433/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: adsfadsfa23421313dfabadsf32rl
    depends_on:
      - umi-db
    restart: always
  umi-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    ports:
      - "5433:5432"
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
    restart: always
volumes:
  umami-db-data:
```
5432 Is already been used by another docker
