### ISSUE TITLE
Unexpected restart

### ISSUE THREAD

**Issue by yumusb** [umami-software/umami#1876]
![image](https://user-images.githubusercontent.com/43062104/230702342-d2bdbc62-be93-4db6-8a44-b00a5693d748.png)

You can see multiple startup logs.
![image](https://user-images.githubusercontent.com/43062104/230702420-483cb0da-dcdc-40ad-ae2c-2b712b3a28df.png)

my docker compose file 
```
version: '3'
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: xxxxxx
      TRACKER_SCRIPT_NAME: main
      DISABLE_UPDATES: 1
      DISABLE_TELEMETRY: 1
      LOG_QUERY: 1
      CLIENT_IP_HEADER: xxxxxx
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
    restart: always
volumes:
  umami-db-data:
```
system  
`Linux version 5.15.0-1030-oracle (buildd@bos02-arm64-061) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #36-Ubuntu SMP Wed Feb 15 05:57:14 UTC 2023`

Is it possible to add an environment variable to enable debug mode?
