### ISSUE TITLE
Umami stops working properly after restart

### ISSUE THREAD

**Issue by GoudronViande24** [umami-software/umami#1889]
I'm using docker compose, fresh install and I use Cloudflare zero trust tunnels to access it.

docker-compose.yml:
```yml
---
version: '3'
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      - db
    restart: always
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - ./umami-db-data:/var/lib/postgresql/data
    restart: always
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=XXXXXXXXXXXXXXXXX
```

Here are the logs:
```
umami-db-1          |
umami-db-1          | PostgreSQL Database directory appears to contain a database; Skipping initialization
umami-db-1          |
umami-db-1          | 2023-04-18 01:52:15.781 UTC [1] LOG:  starting PostgreSQL 15.2 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
umami-db-1          | 2023-04-18 01:52:15.781 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
umami-db-1          | 2023-04-18 01:52:15.781 UTC [1] LOG:  listening on IPv6 address "::", port 5432
umami-db-1          | 2023-04-18 01:52:15.786 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
umami-db-1          | 2023-04-18 01:52:15.794 UTC [23] LOG:  database system was shut down at 2023-04-18 01:51:33 UTC
umami-db-1          | 2023-04-18 01:52:15.800 UTC [1] LOG:  database system is ready to accept connections
umami-umami-1       | yarn run v1.22.19
umami-umami-1       | $ npm-run-all check-db update-tracker start-server
umami-umami-1       | $ node scripts/check-db.js
umami-umami-1       | ✓ DATABASE_URL is defined.
umami-umami-1       | ✓ Database connection successful.
umami-umami-1       | ✓ Database version check successful.
umami-db-1          | 2023-04-18 01:52:17.187 UTC [29] ERROR:  relation "account" does not exist at character 15
umami-db-1          | 2023-04-18 01:52:17.187 UTC [29] STATEMENT:  select * from account limit 1
umami-umami-1       | Prisma schema loaded from prisma/schema.prisma
umami-umami-1       | Datasource "db": PostgreSQL database "umami", schema "public" at "db:5432"
umami-umami-1       |
umami-umami-1       | 1 migration found in prisma/migrations
umami-umami-1       |
umami-umami-1       |
umami-umami-1       | No pending migrations to apply.
umami-umami-1       |
umami-umami-1       | ✓ Database is up to date.
umami-umami-1       | $ node scripts/update-tracker.js
umami-umami-1       | $ node server.js
umami-umami-1       | Listening on port 3000 url: http://ad3546e944a8:3000
umami-umami-1       | error Command failed with signal "SIGSEGV".
umami-umami-1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
umami-umami-1       | ERROR: "start-server" exited with 1.
umami-umami-1       | error Command failed with exit code 1.
umami-umami-1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
umami-umami-1 exited with code 0
umami-umami-1       | yarn run v1.22.19
umami-umami-1       | $ npm-run-all check-db update-tracker start-server
umami-umami-1       | $ node scripts/check-db.js
umami-umami-1       | ✓ DATABASE_URL is defined.
umami-umami-1       | ✓ Database connection successful.
umami-umami-1       | ✓ Database version check successful.
umami-db-1          | 2023-04-18 01:52:46.126 UTC [38] ERROR:  relation "account" does not exist at character 15
umami-db-1          | 2023-04-18 01:52:46.126 UTC [38] STATEMENT:  select * from account limit 1
umami-db-1          | 2023-04-18 01:52:47.175 UTC [39] LOG:  could not receive data from client: Connection reset by peer
umami-db-1          | 2023-04-18 01:52:47.247 UTC [40] LOG:  could not receive data from client: Connection reset by peer
umami-umami-1       | Prisma schema loaded from prisma/schema.prisma
umami-umami-1       | Datasource "db": PostgreSQL database "umami", schema "public" at "db:5432"
umami-umami-1       |
umami-umami-1       | 1 migration found in prisma/migrations
umami-umami-1       |
umami-umami-1       |
umami-umami-1       | No pending migrations to apply.
umami-umami-1       |
umami-umami-1       | ✓ Database is up to date.
umami-umami-1       | $ node scripts/update-tracker.js
umami-umami-1       | $ node server.js
umami-umami-1       | Listening on port 3000 url: http://ad3546e944a8:3000
```
