### ISSUE TITLE
Error running umami in Docker

### ISSUE THREAD

**Issue by mettlong** [umami-software/umami#2172]
### Describe the Bug

Hello, I am currently using a Raspberry 4B model, and I am using Docker and Docker Compose by installing it.

To use umami, I created docker-compose.yml as shown below, and the installation was completed, but an error is occurring when I look at the docker log.

`exec /usr/local/bin/docker-entrypoint.sh: exec format error
`

```
version: '3'
services:
  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: replace-me-with-a-random-string
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
    restart: always
volumes:
  umami-db-data:
```
Does anyone know why this error occurs and how to fix it?

The environment is Ubuntu 22.04.

### Database

PostgreSQL

### Relevant log output

```shell
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

### How are you deploying your application? (if relevant)

Docker
