### ISSUE TITLE
使用docker-compose 部署后 数据库连接有误

### ISSUE THREAD

**Issue by LittleXingzzZ** [umami-software/umami#2211]
### Describe the Bug

用navicat可以连接到数据库，但是数据库上面没有表

### Database

PostgreSQL

### Relevant log output

```shell
08:43:26 ✓ DATABASE_URL is defined.

08:43:31 ✗ Unable to connect to the database.

08:43:31 error Command failed with exit code 1.

08:43:31 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

08:43:31 ERROR: "check-db" exited with 1.

08:43:31 error Command failed with exit code 1.

08:43:31 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### How are you deploying your application? (if relevant)

Docker

**Comment by orilights** [comment]
贴一下你用的 docker-compose 配置？

**Comment by LittleXingzzZ** [comment]
`---
version: '3'
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  umami-db-data:`

**Comment by LittleXingzzZ** [comment]
### 我使用以下docker-compose配置文件 可以成功部署！

```
---
version: '3'
services:
  umami:
    image: docker.umami.dev/umami-software/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      - db
    restart: always
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - ./umami-db-data:/var/lib/postgresql/data
    restart: always
```
