### ISSUE TITLE
Umami crashes continuously since version 2.6.0

### ISSUE THREAD

**Issue by thueske** [umami-software/umami#2278]
### Describe the Bug

Umami crashes continuously since version 2.6.0 (currently 2.6.2). I can't reproduce it and I can't find a way to enable debug output - there's nothing helpful in the log. I now have to restart the containers with "docker compose up -d --force-recreate" at least 1x a day. I could observe the whole thing on two systems (1x with postgres 13 and 1x with psotgres 15).

```
version: "3.5"
services:
  app:
    image: ghcr.io/umami-software/umami:postgresql-latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://umami:umami@db:5432/umami
      - DATABASE_TYPE=postgresql
      - IGNORE_HOSTNAME
      - ENABLE_TEST_CONSOLE=1
      - APP_SECRET
      - DISABLE_TELEMETRY=1
    networks:
      proxy_apps:
      default:
    labels:
      backups: "true"

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=umami
      - POSTGRES_PASSWORD=umami
      - POSTGRES_DB=umami
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      default:
    labels:
      backups: "true"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  proxy_apps:
    name: proxy_apps
    external: true
```

### Database

PostgreSQL

### Relevant log output

```shell
analytics-db-1   |
analytics-db-1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
analytics-db-1   |
analytics-db-1   | 2023-09-05 14:21:23.222 UTC [1] LOG:  starting PostgreSQL 15.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
analytics-db-1   | 2023-09-05 14:21:23.223 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
analytics-db-1   | 2023-09-05 14:21:23.223 UTC [1] LOG:  listening on IPv6 address "::", port 5432
analytics-db-1   | 2023-09-05 14:21:23.228 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
analytics-db-1   | 2023-09-05 14:21:23.237 UTC [24] LOG:  database system was shut down at 2023-09-05 14:21:21 UTC
analytics-db-1   | 2023-09-05 14:21:23.250 UTC [1] LOG:  database system is ready to accept connections
analytics-db-1   | 2023-09-05 14:21:38.175 UTC [37] ERROR:  relation "account" does not exist at character 15
analytics-db-1   | 2023-09-05 14:21:38.175 UTC [37] STATEMENT:  select * from account limit 1
analytics-db-1   | 2023-09-05 14:26:23.333 UTC [22] LOG:  checkpoint starting: time
analytics-db-1   | 2023-09-05 14:26:23.360 UTC [22] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.003 s, total=0.027 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB
analytics-app-1  | yarn run v1.22.19
analytics-app-1  | $ npm-run-all check-db update-tracker start-server
analytics-app-1  | $ node scripts/check-db.js
analytics-app-1  | ✓ DATABASE_URL is defined.
analytics-app-1  | ✓ Database connection successful.
analytics-app-1  | ✓ Database version check successful.
analytics-app-1  | Prisma schema loaded from prisma/schema.prisma
analytics-app-1  | Datasource "db": PostgreSQL database "umami", schema "public" at "db:5432"
analytics-app-1  |
analytics-app-1  | 3 migrations found in prisma/migrations
analytics-app-1  |
analytics-app-1  |
analytics-app-1  | No pending migrations to apply.
analytics-app-1  |
analytics-app-1  | ✓ Database is up to date.
analytics-app-1  | $ node scripts/update-tracker.js
analytics-app-1  | $ node server.js
analytics-app-1  | - ready started server on 192.168.80.3:3000, url: http://192.168.80.3:3000
```
