### ISSUE TITLE
Dependency failed to start: container umami-db is unhealthy

### ISSUE THREAD

**Issue by anseltaft** [umami-software/umami#2280]
### Describe the Bug

I used the [docker-compose.yml file from the base of the Umami repository](https://github.com/umami-software/umami/blob/master/docker-compose.yml) with a few edits:

```
version: "3.4"

services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
#   image: docker.umami.dev/umami-software/umami:postgresql-latest
    container_name: umami
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - frontendproxy
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: [edited out]
      TRACKER_SCRIPT_NAME: [edited out]
      IGNORE_IP: [edited out]
    labels:
      - traefik.enable=true
      - traefik.http.routers.umami.rule=Host(`[edited out]`)
      - traefik.http.routers.umami.entrypoints=https
      - traefik.http.routers.umami.tls.certresolver=cloudflare"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  db:
    image: postgres:15-alpine
    container_name: umami-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "10"
volumes:
  umami-db-data:
networks:
  frontendproxy:
    external: true
```

I'm obviously using traefik with Umami, but the problem is with the database. Each time I start it up I see:
[+] Running 3/3
 ✔ Network umami_default  Created                                                                                                     0.1s 
 ✘ Container umami-db     Error                                                                                                       0.6s 
 ✔ Container umami        Created                                                                                                     0.0s 
dependency failed to start: container umami-db is unhealthy

I've taken the containers down, nuked the images, and rebuilt everything with the --build switch and yet I can't get the database to come up right. I've also tried the 12-alpine and 14-alpine images to no avail. The OS is Debian 11 and I've tried running everything as both my user (who's in the docker group, with rootless mode activated) and as root.

### Database

PostgreSQL

### Relevant log output

```shell
[+] Running 3/3
 ✔ Network umami_default  Created                                                                                                     0.1s 
 ✘ Container umami-db     Error                                                                                                       0.6s 
 ✔ Container umami        Created                                                                                                     0.0s 
dependency failed to start: container umami-db is unhealthy
```

### How are you deploying your application? (if relevant)

Docker compose on Debian 11
