### ISSUE TITLE
Cannot access websites page in 2.7.0

### ISSUE THREAD

**Issue by Korhm** [umami-software/umami#2310]
### Describe the Bug

Hello,

I just installed v2.7.0 via Docker.
I cannot access the websites page, I got a blank white page.

There is an error in the dev console :
```
 Error: Failed to lookup route: /settings
    at /_next/static/chunks/main-56afab9f90f97dc9.js:1:26985
```

I'm using latest verion of Brave browser, but same issue with other browsers like Firefox

### Database

PostgreSQL

### Relevant log output

```shell
Error: Failed to lookup route: /settings
    at /_next/static/chunks/main-56afab9f90f97dc9.js:1:26985
```

### Which browser are you using? (if relevant)

Brave

### How are you deploying your application? (if relevant)

Docker

**Comment by jmodrako** [comment]
Have similar issue, in the dev tools I can see that this path return 404: 

`_next/static/chunks/pages/websites/%5Bid%5D-564d8b0efa348841.js`

**Comment by franciscao633** [comment]
Is this a fresh install or an upgrade? I couldn't reproduce the error when running the compose file.

**Comment by Korhm** [comment]
It's a fresh install.

I missundestood the documentation I thing.
The page for ennvironment variables (https://umami.is/docs/environment-variables) let met think the default value for `CLOUD_MODE` is `1`, so I set `0`
It seems that it also disable some pages, but withtout explicite message.

Where can I find default values for env ?

**Comment by franciscao633** [comment]
For a fresh install you really only need the DATABASE_URL env var. The others are for an as needed basis, so you can just leave them out.

**Comment by SirYuxuan** [comment]
Hello brother, have you solved your problem

**Comment by orhun** [comment]
I'm having the same problem. Here is my `docker-compose.yml`:

```yml
version: "3"
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-v2.7.0
    container_name: umami
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: ...
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: postgres:12-alpine
    container_name: umami_db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
```

I recently migrated from v1 and tested it on my local which works fine. But when I deploy it to my website I get:

```
Loading failed for the <script> with source “https://umami.orhun.dev/_next/static/chunks/pages/websites/%5Bid%5D-7f6923e98632cfd3.js”.
```

As a workaround, I downgraded to `2.5.0` and now everything works.

**Comment by SirYuxuan** [comment]
> I'm having the same problem. Here is my `docker-compose.yml`:
> 
> ```yaml
> version: "3"
> services:
>   umami:
>     image: ghcr.io/umami-software/umami:postgresql-v2.7.0
>     container_name: umami
>     ports:
>       - "3000:3000"
>     environment:
>       DATABASE_URL: postgresql://umami:umami@db:5432/umami
>       DATABASE_TYPE: postgresql
>       APP_SECRET: ...
>     depends_on:
>       db:
>         condition: service_healthy
>     restart: always
>   db:
>     image: postgres:12-alpine
>     container_name: umami_db
>     environment:
>       POSTGRES_DB: umami
>       POSTGRES_USER: umami
>       POSTGRES_PASSWORD: umami
>     volumes:
>       - ./umami-db-data:/var/lib/postgresql/data
>     restart: always
>     healthcheck:
>       test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
>       interval: 5s
>       timeout: 5s
>       retries: 5
> ```
> 
> I recently migrated from v1 and tested it on my local which works fine. But when I deploy it to my website I get:
> 
> ```
> Loading failed for the <script> with source “https://umami.orhun.dev/_next/static/chunks/pages/websites/%5Bid%5D-7f6923e98632cfd3.js”.
> ```
> 
> As a workaround, I downgraded to `2.5.0` and now everything works.

Thanks for the solution, everything is fine for me after downgrading to 2.5.0

**Comment by orhun** [comment]
`2.8.0` has the same issue, with a more visible error message:

![image](https://github.com/umami-software/umami/assets/24392180/4b02d9b5-025b-4e0c-9afc-51bf1fbd927f)

**Comment by mikecao** [comment]
@orhun Are you using docker or building from source?

**Comment by orhun** [comment]
I'm using the `docker-compose.yml` file that I shared above.

**Comment by artfulrobot** [comment]
Follow. I'm using the docker-compose method and after an upgrade (via `docker-compose up -d`) I can't get to any of my sites. It seems the error is the same: the browser is trying to load .js from a URL that contains `[id]` when I suppose that's an un-expanded token.

**Comment by SirYuxuan** [comment]
> Thanks for the solution, everything
I downloaded the 2.5.0 source code directly and compiled it and it works fine!

**Comment by corentin35000** [comment]
Works by downgrading to version 2.5.0 for Umami I tried all the higher versions it does not actually work

**Comment by artfulrobot** [comment]
This seems pretty serious!  :worried:  **Three point releases that don't work, then?**

- 2.5 we all say works.
- 2.6: I haven't tested has anyone else?
- 2.7: Didn't work for me
- 2.8: didn't work for me.

**Comment by orhun** [comment]
Yes, tested the other ones and only 2.5 works for me.

**Comment by corentin35000** [comment]
Yes, as I said previously I tested all versions > 2.5.0 and none of the versions work

**Comment by Korhm** [comment]
Hello everybody

The issue I had with version 2.7.0 was because I missunderstood the usage of env variable `CLOUD_MODE` 
I force it to value `0`, but it seems that even with these value, the cloud mode is on, and the some page are not accessible
Once I removed this env variable, everything ran fine (and still is) with version 2.7.0 (did not test 2.8.0)

If it can help, here is the docker-compose.yml I'm using:
```
version: '3.8'

services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    environment:
      DISABLE_BOT_CHECK: 1
      ENABLE_TEST_CONSOLE: 0
      DISABLE_TELEMETRY: 1
      DISABLE_UPDATES: 1
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_umami:5432/${POSTGRES_DB}
      IGNORE_IP: ${IGNORE_IP}
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.umami.entrypoints=https'
      - 'traefik.http.routers.umami.rule=Host(`********`)'
      - 'traefik.http.services.umami.loadbalancer.server.port=3000'
    networks:
      - traefik-net
      - umami-backend

  db_umami:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - umami-backend

networks:
  traefik-net:
    external: true
  umami-backend:
```
