### ISSUE TITLE
ALLOWED_FRAME_URLS and other env variables are not used. 

### ISSUE THREAD

**Issue by noximo** [umami-software/umami#2407]
### Describe the Bug

Hello, 

I'm trying to display analytics inside an iframe. 

For that reason, I set up ALLOWED_FRAME_URLS environment variable using docker compose.

But the app doesn't use it. 
The header is
`Content-Security-Policy: default-src 'self'; img-src *; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' api.umami.is; frame-ancestors 'self' undefined;`
Where the undefined at the end is supposed to be the content of the variable, as per: https://github.com/umami-software/umami/blob/8a4623eb7ba8d84405896d14949473a90cb3e37f/next.config.js#L12)

I've tried setting FORCE_SSL as well, with the same result. 

If I exec into docker container directly and then into node, I can see both variables just fine. Other variables (like db URL) work fine. 

Here's my docker-compose definition:

```
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_UNAMI_DB:-unami}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}
      DATABASE_TYPE: postgresql
      APP_SECRET: ${UNAMI_RANDOM_STRING:-unami_random}
      ALLOWED_FRAME_URLS: https://localhost
      FORCE_SSL: 1
    depends_on:
      - database
    restart: always
```

Am I doing something wrong? 

Thank you for your help. 
 

### Database

PostgreSQL

### Which browser are you using? (if relevant)

not relevant

### How are you deploying your application? (if relevant)

Docker
