### ISSUE TITLE
A problem has occurred

### ISSUE THREAD

**Issue by quick-tutoriel** [umami-software/umami#2591]
### Describe the Bug

Hello,

I use umami under docker and I have a problem when I select a large time interval (this year for example).
The graphs are not displayed and I get an error message: A problem has occurred.

I'm using 
![umami-error](https://github.com/umami-software/umami/assets/4949554/748d8834-f778-4660-b556-b8673ccf12c2)

### Database

MySQL

### Which Umami version are you using? (if relevant)

V2.10.2

### Which browser are you using? (if relevant)

Brave

### How are you deploying your application? (if relevant)

Docker

**Comment by franciscao633** [comment]
Since your using Docker, you may need to increase the shared memory size for the mysql container. Example for psql, add `shm_size: 1gb `. You will need to recreate your container after adding the line.

```
  db:
    image: postgres:15-alpine
    shm_size: 1gb 
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
```
