### ISSUE TITLE
Generating a User Journey throws an Internal Server Error

### ISSUE THREAD

**Issue by PeeK1e** [umami-software/umami#2800]
### Describe the Bug

As Tile says.

1. Updated to the new v2.12.0 update. (Image: `docker.umami.is/umami-software/umami:postgresql-v2.12.0`)
2. Going to Reports > Create Report > Journey > {website} / {any timerange} > Run Query
3. Throws an *Internal Server Error*

The environment is not critical, just for my personal use. I can rollback with an database dump and test some other stuff if that is necessary :)

Tested it in Firefox and Brave, disabled extensions and uBlock etc.

### Database

PostgreSQL

### Relevant log output

```shell
#### CONTAINER LOG ####
PrismaClientKnownRequestError: 
Invalid `prisma.$queryRawUnsafe()` invocation:

Raw query failed. Code: `42601`. Message: `ERROR: syntax error at or near "event"`
    at In.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6877)
    at In.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6211)
    at In.request (/app/node_modules/@prisma/client/runtime/library.js:122:5919)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async l (/app/.next/server/pages/api/reports/journey.js:1:2025)
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:600:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:816:17) {
  code: 'P2010',
  clientVersion: '5.14.0',
  meta: { code: '42601', message: 'ERROR: syntax error at or near "event"' }
}
```

### Which Umami version are you using? (if relevant)

v2.12.0

### Which browser are you using? (if relevant)

Firefox, Brave

### How are you deploying your application? (if relevant)

Kubernetes (Container/Docker)

**Comment by franciscao633** [comment]
There were no DB migrations this release, so no rollback of the database should be needed. I'm having a hard time reproducing it. What version of postgresql are you on? We use raw sql for the journey's query and it seems to be syntax with your instance vs mine, so trying to track it down.

**Comment by PeeK1e** [comment]
Thanks for the fast reply :slightly_smiling_face: 
Using the Postgresoperator from Zalando to rollout databases
the current version is: `PostgreSQL 13.10 (Ubuntu 13.10-1.pgdg22.04+1) on aarch64-unknown-linux-gnu`

i can try to update it to 14

**Comment by PeeK1e** [comment]
I created a Postgre cluster with `PostgreSQL 15.2`. There it seems to work with the same data, so it seems like Postgre 13 has issues with the queries.

**Comment by PeeK1e** [comment]
Okay, I have tested it with Postgres `12.14`, `13`, `14` and `15`.
On `14` and `15` the journeys work.
On the other versions it reliably throws an `Internal Server Error`.

I have tested it with the compose and mounted files below.
For me the issue is solved and can be closed since I just upgraded to Postgres 15.

`compose.yaml`
```yaml
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-v2.12.0
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://umami:umami@db:5432/umami"
      DATABASE_TYPE: "postgresql"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - postgres_data:/var/lib/postgresql/data

  caddy:
    image: caddy:latest
    ports:
      - "8080:80"
    volumes:
      - ./site:/usr/share/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  postgres_data:
```
`./site/index.html`
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My Static Site</title>
  <!-- Umami tracking script -->
<script defer src="http://localhost:3000/script.js" data-website-id="YOUR_ID"></script>
</head>
<body>
  <h1>Welcome to My Static Site</h1>
  <p>This is a simple static website served by Caddy with Umami analytics.</p>
</body>
</html>
```
`Caddyfile`
```Caddyfile
:80 {
  root * /usr/share/caddy
  file_server
}
```
