### ISSUE TITLE
Allow different env vars for the same configuration

### ISSUE THREAD

**Issue by luizkowalski** [umami-software/umami#3078]
### Describe the feature or enhancement

This might be too specific but I think there is still value: Umami should expect different env vars for the same configuration.

Example: I'm deploying an application with [Kamal](https://kamal-deploy.org/docs/configuration/overview/) and one of the "accessories" I'm deploying too is Umami. Kamal loads the the env vars from a single file so I can't have duplicates and both my app and Umami expect `DATABASE_URL` and they are not the same so for Umami I have to do some workaround:

```yaml
<% require "dotenv"; Dotenv.load(".kamal/secrets") %> 
  umami:
    image: umamisoftware/umami:postgresql-v2.14.0
    port: 3000
    hosts:
      - web
    env:
      clear:
        DATABASE_URL: <%= ENV["UMAMI_DATABASE_URL"] %>
...
```

My point is that `DATABASE_URL` (and other env vars like `PORT` for example) are usually too generic and a lot other services and applications might expect the same var. Ideally, such variables should also be accessible with `UMAMI_` as `UMAMI_DATABASE_URL` and `UMAMI_PORT`. [Filebrowser](https://filebrowser.org/cli/filebrowser#synopsis) does something like this, it prepepnds `FB_` to every possible env var too.

not sure if I'm being clear, let me know how does this sound!
