### ISSUE TITLE
CLOUD_MODE not working

### ISSUE THREAD

**Issue by the-leonat** [umami-software/umami#3291]
### Describe the Bug

Hello, 

im trying to get env variable `CLOUD_MODE` to work without success. I would expect the setting to disable websites, users and teams as stated in the docs. I do run umami with docker-compose, where I tried a custom build, with CLOUD_MODE as a build variable. All with no success.

I also tried `CLOUD_MODE=1`,  `CLOUD_MODE="1"`, `CLOUD_MODE=0`, `CLOUD_MODE=""`, `CLOUD_MODE=`

```
services:
  umami:
    build:
      context: 'https://github.com/umami-software/umami.git'
      args:
        - CLOUD_MODE=1
        - DATABASE_TYPE=postgres
    image: 'umami:postgresql-latest-custom'
    pull_policy: never
    environment:
      - SERVICE_FQDN_UMAMI_3000
      - 'DATABASE_URL=postgres://$SERVICE_USER_POSTGRES:$SERVICE_PASSWORD_POSTGRES@postgresql:5432/$POSTGRES_DB'
      - DATABASE_TYPE=postgres
      - APP_SECRET=$SERVICE_PASSWORD_64_UMAMI
      - CLOUD_MODE=1
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:3000/api/heartbeat'
      interval: 5s
      timeout: 20s
      retries: 10
  postgresql:
    image: 'postgres:16-alpine'
    volumes:
      - 'postgresql-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - 'POSTGRES_DB=${POSTGRES_DB:-umami}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
```

### Database

PostgreSQL

### Relevant log output

```shell

```

### Which Umami version are you using? (if relevant)

latest

### How are you deploying your application? (if relevant)

docker-compose, coolify
