### ISSUE TITLE
ERROR: "check-db" exited with 1.

### ISSUE THREAD

**Issue by quick-tutoriel** [umami-software/umami#3408]
### Describe the Bug

Hello,

with docker I went from a V2.17 image to V2.18 and when rebooting the umami container I get this error and I can't resolve it: 
```
ERROR: "check-db" exited with 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
yarn run v1.22.22
$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database version check successful.
Error: P3009
migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `09_update_hostname_region` migration started at 2025-05-09 16:08:47.366687 UTC failed
✗ Command failed: prisma migrate deploy
Error: P3009
migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `09_update_hostname_region` migration started at 2025-05-09 16:08:47.366687 UTC failed
```
 
I tried to go back to V2.17 and I have the same problem.

Can you help me?

Thanks

### Database

PostgreSQL

### Relevant log output

```shell

```

### Which Umami version are you using? (if relevant)

V.2.18

### Which browser are you using? (if relevant)

Brave

### How are you deploying your application? (if relevant)

Docker

**Comment by serversathome** [comment]
same problem here.

**Comment by quejas** [comment]
Hello, same here, did you find a solution?

**Comment by KieranP** [comment]
Looks like the migration runs in a transaction, so it locks the tables while running. Because of this, the migration took 15+ minutes to run for me while it updated the table and every row, but eventually it did complete. It is important not to restart docker or do anything that would disrupt the migration.

**Comment by serversathome** [comment]
@KieranP i dont think that will work for me. it looks like its just looping in my logs. thoughts? https://pastebin.com/E3NdtGLk

**Comment by KieranP** [comment]
@serversathome I see this toward the top of the logs:

```
2025-05-09 11:26:19.987 UTC [1] LOG:  received fast shutdown request
2025-05-09 11:26:20.014 UTC [1] LOG:  aborting any active transactions
2025-05-09 11:26:20.014 UTC [45] FATAL:  terminating connection due to administrator command
```

This indicates that docker received a command to shutdown or restart a container. Assuming you didn't issue the command yourself, it could be a timeout or memory issue. When docker restarts, the database migration is cancelled, but the row in the_prisma_migrations table is retained. So when docker tries to autostart the umami container again, prisma (the DB wrapper umami uses) sees a failed migration and aborts, killing the container, which docker then restarts, repeats, repeats, repeats.

Couple of things to try:
1) Make sure you don't have any timeouts on the docker container startup that could be killing the container before it's ready. Some docker configs use a health check that pings the HTTP server to make sure its online. Since the HTTP server wont be online until after migrations, it's possible any health check is restarting the container during the migration
2) Make sure docker has enough memory. The migration seems to be run in a single transaction, so it needs to lock the table and store all changes in memory, and only once all changes are calculated will it save those changes to the DB. I don't know enough about postgres/myself, but I would imagine migrations of this scale would require a lot of memory. If memory limits are hit, docker may restart the container, aborting the migration part way through.

**Comment by serversathome** [comment]
@KieranP this is my docker compose. do u think those health checks are breaking this?

```
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-v2.17
    #image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    ports:
      - 3002:3000
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - curl http://localhost:3000/api/heartbeat
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:15-alpine
    container_name: umami-db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - /mnt/bigdeal/configs/umami/umami-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5
```
