### ISSUE TITLE
Cloud offering version is not giving correct Country location of the user. (It is always showing France for every user.)

### ISSUE THREAD

**Issue by samyogdhital** [umami-software/umami#3478]
### Describe the Bug

I am using cloud offering version of umami not self hosted one.

When I check my Umami dashboard, all visits are logged with IPs that geolocate to France (presumably Cloudflare’s proxy). I’m accessing from Nepal.

Tech Stack.
- Nextjs frontend deployed into my own vps as standalone docker container.
- Traefik is used as the reverse proxy in front of the container.
- Using cloudflare with proxy (orange color) dns to vps Ip address. (I have also enabled /`Allow visitors location headers`)
- I haved added rewrite to nextjs config to proxy the umami url to my own url.

The events am tracking are perfectly, but the location is always displayed as France. This issue does not occur when I am working on localhost; during development, the country is accurately tracked as my current location. However, once deployed, it is tracking IP address of my vps or whatever, resulting location showing france alwasy.. I have conducted extensive research online but have been unable to find a definitive solution to this problem.

This is my traefik's docker compose file.
```
services:
  traefik:
    image: traefik:latest
    container_name: 100xvoice-traefik
    restart: unless-stopped
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.network=100xvoice"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--api.insecure=false"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
```

This is my frontend nextjs's docker compose file.

```
services:
  web:
    image: samyogdhital/homepage:latest
    container_name: homepage
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.com`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls.certresolver=cloudflare"
      - "traefik.http.services.homepage.loadbalancer.server.port=2083"
      - "traefik.http.routers.homepage.middlewares=homepage-secure-headers@docker"
      - "traefik.http.middlewares.homepage-secure-headers.headers.SSLRedirect=false"
      - "traefik.http.middlewares.homepage-secure-headers.headers.STSSeconds=315360000"
      - "traefik.http.middlewares.homepage-secure-headers.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.homepage-secure-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.homepage-secure-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.homepage-secure-headers.headers.SSLHost=homepage.com"
      - "traefik.http.middlewares.homepage-secure-headers.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.homepage-secure-headers.headers.STSPreload=true"
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true 
```

### Database

Umami Cloud

### Relevant log output

```shell

```

### Which Umami version are you using? (if relevant)

cloud version

### Which browser are you using? (if relevant)

edge, chrome

### How are you deploying your application? (if relevant)

docker traefik cloudflare
