### ISSUE TITLE
[Next.js startup error in Docker Swarm] - "ELIFECYCLE  Command failed" error.

### ISSUE THREAD

**Issue by silvioes** [umami-software/umami#3491]
### Describe the Bug

Umami container fails to start with an "ELIFECYCLE  Command failed." error, the database container seems to be running fine, all migrations runs without any error however the Next.js app fails to start.

My Docker Compose file to deploy Umami behind Traefik with Docker Swarm `docker stack deploy --compose-file compose.yml umami -d` command.
```yaml
---
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-v2.18.1
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_TYPE: postgresql
      APP_SECRET: ${APP_SECRET}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.umami.tls=true
        - traefik.http.routers.umami.tls.certresolver=cloudflare
        - traefik.http.routers.umami.entrypoints=websecure
        - traefik.http.routers.umami.rule=Host(`umami.domain`)
        - traefik.http.services.umami.loadbalancer.server.port=3000
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - proxy_traefik
    init: true
    healthcheck:
      test: ["CMD-SHELL", "curl http://umami:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    networks:
      - proxy_traefik
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  umami-db-data:

networks:
  proxy_traefik:
    external: true

```

I was only able to get it working by downgrading the Umami image version to [postgresql-v2.17](https://github.com/orgs/umami-software/packages/container/umami/370155582?tag=postgresql-v2.17) without any other changes to the Docker Compose file. However, I would still like to update the image in the future.

### Database

PostgreSQL

### Relevant log output

```shell
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | > umami@2.18.1 start-docker /app
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | > npm-run-all check-db update-tracker set-routes-manifest start-server
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | > umami@2.18.1 check-db /app
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | > node scripts/check-db.js
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | ✓ DATABASE_URL is defined.
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | ✓ Database connection successful.
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | ✓ Database version check successful.
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | Prisma schema loaded from prisma/schema.prisma
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | Datasource "db": PostgreSQL database "umami", schema "public" at "db:5432"
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | 10 migrations found in prisma/migrations
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | Applying migration `01_init`
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | Applying migration `02_report_schema_session_data`
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | Applying migration `03_metric_performance_index`
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | Applying migration `04_team_redesign`
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | Applying migration `05_add_visit_id`
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | Applying migration `06_session_data`
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | Applying migration `07_add_tag`
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | Applying migration `08_add_utm_clid`
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | Applying migration `09_update_hostname_region`
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | Applying migration `10_add_distinct_id`
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | The following migration(s) have been applied:
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | migrations/
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |   └─ 01_init/
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |     └─ migration.sql
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |   └─ 02_report_schema_session_data/
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |     └─ migration.sql
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |   └─ 03_metric_performance_index/
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |     └─ migration.sql
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |   └─ 04_team_redesign/
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |     └─ migration.sql
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |   └─ 05_add_visit_id/
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |     └─ migration.sql
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |   └─ 06_session_data/
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |     └─ migration.sql
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |   └─ 07_add_tag/
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |     └─ migration.sql
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |   └─ 08_add_utm_clid/
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |     └─ migration.sql
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |   └─ 09_update_hostname_region/
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |     └─ migration.sql
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |   └─ 10_add_distinct_id/
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |     └─ migration.sql
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | All migrations have been successfully applied.
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | ✓ Database is up to date.
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | > umami@2.18.1 update-tracker /app
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | > node scripts/update-tracker.js
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | > umami@2.18.1 set-routes-manifest /app
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | > node scripts/set-routes-manifest.js
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | Using original Next.js routes manifest
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | > umami@2.18.1 start-server /app
umami_umami.1.yp5imzoacimb@server-ges-apps-01    | > node server.js
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |    ▲ Next.js 15.3.1
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |    - Local:        http://localhost:3000
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |    - Network:      http://0.0.0.0:3000
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |  ✓ Starting...
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |  ✓ Ready in 199ms
umami_umami.1.yp5imzoacimb@server-ges-apps-01    |  ELIFECYCLE  Command failed.
```

### Which Umami version are you using? (if relevant)

2.18.1

### How are you deploying your application? (if relevant)

Docker Swarm
